# Generated by Django 5.1.3 on 2024-11-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='name',
        ),
    ]
