# Generated by Django 5.1.3 on 2024-11-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_rename_title_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(to='plants.category'),
        ),
    ]
